export const godot = {
  name: 'Godot',
  url: 'https://godotengine.org/',
  repo: 'godotengine/godot',
  stars: 56_000,
}

export const engines = {
  three: {
    name: 'Three.js',
    repo: 'mrdoob/three.js',
    url: 'https://threejs.org',
    npm: 'three',
    stars: 95_000,
    downloads: 1_000_000,
  },
  pixi: {
    name: 'PixiJS',
    repo: 'pixijs/pixijs',
    url: 'https://pixijs.com',
    stars: 41_000,
    downloads: 105_000,
    npm: 'pixi.js',
  },
  phaser: {
    name: 'Phaser',
    url: 'https://phaser.io',
    repo: 'photonstorm/phaser',
    stars: 35_000,
    downloads: 16_000,
    npm: 'phaser',
  },
  babylon: {
    name: 'Babylon.js',
    url: 'https://www.babylonjs.com',
    repo: 'BabylonJS/Babylon.js',
    stars: 22_000,
    downloads: 30_000,
    npm: '@babylonjs/core',
  },
  playcanvas: {
    name: 'PlayCanvas',
    url: 'https://playcanvas.com',
    repo: 'playcanvas/engine',
    stars: 9_000,
    // downloads: 2_000,
    npm: 'playcanvas',
  },
  ogl: {
    url: 'https://oframe.github.io/ogl/examples/',
    name: 'OGL',
    repo: 'oframe/ogl',
    stars: 3300,
    npm: 'ogl',
    downloads: 12_000,
  },
  kaboom: {
    name: 'Kaboom',
    url: 'https://kaboomjs.com',
    repo: 'replit/kaboom',
    stars: 2200,
    npm: 'kaboom',
    downloads: 5000,
  },
  two: {
    name: 'Two.js',
    url: 'https://two.js.org',
    repo: 'jonobr1/two.js',
    stars: 8000,
    npm: 'two.js',
    downloads: 3500,
  },
  excalibur: {
    name: 'Excalibur',
    url: 'https://excaliburjs.com/',
    repo: 'excaliburjs/Excalibur',
    stars: 1400,
    downloads: 1200,
    npm: 'excalibur',
  },
  kontra: {
    name: 'Kontra',
    url: 'https://straker.github.io/kontra/',
    repo: 'straker/kontra',
    stars: 800,
    npm: 'kontra',
    downloads: 400,
  },
  melon: {
    name: 'melonJS',
    url: 'https://melonjs.org',
    repo: 'melonjs/melonJS',
    stars: 5500,
    npm: 'melonjs',
    downloads: 200,
  },
  impact: {
    name: 'Impact',
    url: 'https://impactjs.com/',
    lastCommitDate: '2014-07-28',
    repo: 'phoboslab/impact',
    stars: 1900,
  },
  aframe: {
    name: 'A-Frame',
    url: 'https://aframe.io',
    repo: 'aframevr/aframe',
    stars: 16_000,
    downloads: 11_000,
    npm: 'aframe',
  },
}

export const hybridEngines = {
  needle: {
    name: 'Needle',
    url: 'https://needle.tools/',
    npm: '@needle-tools/engine',
    downloads: 440,
    isNew: true,
  },
  spline: {
    url: 'https://spline.design/',
    name: 'Spline',
    npm: '@splinetool/runtime',
    downloads: 69_000,
  },
  cocosCreator: {
    name: 'Cocos Creator',
    url: 'https://www.cocos.com/en/creator',
    repo: 'cocos/cocos-engine',
    stars: 3500,
  },
  cocos2dx: {
    name: 'Cocos2d-x',
    url: 'https://www.cocos.com/en/cocos2d-x',
    repo: 'cocos2d/cocos2d-x',
    stars: 16800,
    lastCommitDate: '2020-01-06',
  },
  construct: {
    name: 'Construct 3',
    url: 'https://www.construct.net/',
  },
  filament: {
    name: 'Filament',
    url: 'https://google.github.io/filament/',
    repo: 'google/filament',
    stars: 15_000,
  },
  gdevelop: {
    name: 'GDevelop',
    url: 'https://gdevelop.io/',
    repo: '4ian/GDevelop',
    stars: 4600,
  },
}

export const poimandres = {
  r3f: {
    name: 'React Three Fiber',
    url: 'https://docs.pmnd.rs/react-three-fiber',
    repo: 'pmndrs/react-three-fiber',
    npm: '@react-three/fiber',
    stars: 24_000,
    downloads: 210_000,
  },
  drei: {
    name: 'Drei',
    repo: 'pmndrs/drei',
    npm: '@react-three/drei',
    stars: 4200,
    downloads: 76_000,
  },
  reactSpring: {
    name: 'react-spring',
    url: 'https://react-spring.dev',
    repo: 'pmndrs/react-spring',
    npm: 'react-spring',
    stars: 25_000,
    downloads: 682_000,
  },
  leva: {
    name: 'Leva',
    url: 'https://leva.pmnd.rs/',
    repo: 'pmndrs/leva',
    npm: 'leva',
    stars: 3300,
    downloads: 19_000,
  },
  gltfjsx: {
    name: 'gltfjsx',
    url: 'https://gltf.pmnd.rs',
    repo: 'pmndrs/gltfjsx',
    stars: 2600,
    npm: 'gltfjsx',
    // Not putting downloads as it's not relevant
  },
  threeStdlib: {
    name: 'three-stdlib',
    repo: 'pmndrs/three-stdlib',
    npm: 'three-stdlib',
    stars: 400,
    downloads: 82_000,
  },
  cannonEs: {
    name: 'cannon-es',
    repo: 'pmndrs/cannon-es',
    stars: 1200,
    downloads: 9000,
    npm: 'cannon-es',
  },
  useCannon: {
    name: 'use-cannon',
    repo: 'pmndrs/use-cannon',
    npm: '@react-three/cannon',
    stars: 2300,
    downloads: 7000,
  },
  postprocessing: {
    name: 'postprocessing',
    repo: 'pmndrs/postprocessing',
    npm: 'postprocessing',
    stars: 1600,
    downloads: 26_000,
  },
  reactPostprocessing: {
    name: 'react-postprocessing',
    repo: 'pmndrs/react-postprocessing',
    npm: '@react-three/postprocessing',
    stars: 700,
    downloads: 13_000,
  },
  reactXR: {
    name: 'react-xr',
    repo: 'pmndrs/react-xr',
    npm: '@react-three/xr',
    stars: 1400,
    downloads: 1400,
  },
  reactThreeNext: {
    name: 'react-three-next',
    url: 'https://react-three-next.vercel.app/',
    repo: 'pmndrs/react-three-next',
    stars: 1000,
  },
  reactThreeFlex: {
    name: 'react-three-flex',
    repo: 'pmndrs/react-three-flex',
    npm: '@react-three/flex',
    stars: 1400,
    downloads: 900,
  },
  reactThreeEditor: {
    name: 'react-three-editor',
    repo: 'pmndrs/react-three-editor',
    stars: 500,
    npm: '@react-three/editor',
    downloads: 700,
    isNew: true,
  },
  lamina: {
    name: 'Lamina',
    repo: 'pmndrs/lamina',
    npm: 'lamina',
    stars: 800,
    downloads: 1400,
  },
  reactThreeRapier: {
    name: 'react-three-rapier',
    repo: 'pmndrs/react-three-rapier',
    npm: '@react-three/rapier',
    stars: 300,
    downloads: 1600,
    isNew: true,
  },
  zustand: {
    name: 'Zustand',
    repo: 'pmndrs/zustand',
    npm: 'zustand',
    stars: 25_000,
    downloads: 914_000,
  },
  jotai: {
    name: 'Jotai',
    repo: 'pmndrs/jotai',
    npm: 'jotai',
    stars: 10_500,
    downloads: 189_000,
  },
  valtio: {
    name: 'Valtio',
    repo: 'pmndrs/valtio',
    npm: 'valtio',
    stars: 5700,
    downloads: 59_000,
  },
}

export const theatre = {
  name: 'Theatre.js',
  url: 'https://www.theatrejs.com/',
  repo: 'theatre-js/theatre',
  npm: '@theatre/core',
  stars: 9000,
  downloads: 700,
  isNew: true,
}

export const particles = {
  nebula: {
    url: 'https://three-nebula.org/',
    name: 'Nebula',
    repo: 'creativelifeform/three-nebula',
    npm: 'three-nebula',
    stars: 600,
    downloads: 800,
    lastCommitDate: '2021-11-05',
  },
  proton: {
    url: 'https://drawcall.github.io/three.proton/',
    name: 'three.proton',
    repo: 'drawcall/three.proton',
    stars: 400,
    npm: 'three.proton.js',
    downloads: 50,
    lastCommitDate: '2020-07-29',
  },
  quarks: {
    name: 'three.quarks',
    repo: 'Alchemist0823/three.quarks',
    stars: 50,
    npm: 'three.quarks',
    downloads: 200,
  },
}

export const debugUI = {
  controlKit: {
    name: 'ControlKit',
    repo: 'automat/controlkit.js',
    stars: 750,
    npm: 'controlkit',
    downloads: 30,
    lastCommitDate: '2016-07-30',
  },
  controlPanel: {
    name: 'control-panel',
    repo: 'freeman-lab/control-panel',
    npm: 'control-panel',
    stars: 200,
    downloads: 10,
    lastCommitDate: '2018-10-21',
  },
  datGui: {
    name: 'dat.GUI',
    repo: 'dataarts/dat.gui',
    npm: 'dat.gui',
    stars: 6_500,
    downloads: 25_000,
    lastCommitDate: '2022-02-19',
  },
  guify: {
    url: 'https://jons.website/projects/guify/',
    name: 'Guify',
    repo: 'colejd/guify',
    lastCommitDate: '2021-12-21',
    stars: 200,
    npm: 'guify',
    downloads: 600,
  },
  leva: poimandres.leva,
  lilGui: {
    url: 'https://lil-gui.georgealways.com/',
    name: 'lil-gui',
    repo: 'georgealways/lil-gui',
    stars: 500,
    npm: 'lil-gui',
    downloads: 45_000,
  },
  oui: {
    name: 'Oui',
    repo: 'wearekuva/oui',
    npm: 'ouioui',
    stars: 300,
    downloads: 10,
    lastCommitDate: '2018-04-03',
  },
  reactDatGui: {
    name: 'React dat.GUI',
    npm: 'react-dat-gui',
    repo: 'claus/react-dat-gui',
    stars: 300,
    downloads: 1300,
    lastCommitDate: '2021-03-30',
  },
  tweakpane: {
    url: 'https://cocopon.github.io/tweakpane/',
    name: 'Tweakpane',
    repo: 'cocopon/tweakpane',
    npm: 'tweakpane',
    stars: 2400,
    downloads: 5000,
  },
  uil: {
    url: 'https://lo-th.github.io/uil/',
    name: 'Uil',
    repo: 'lo-th/uil',
    stars: 500,
    npm: 'uil',
    downloads: 10,
  },
}

export const uiLibraries = {
  react: {
    url: 'https://reactjs.org/',
    name: 'React',
    repo: 'facebook/react',
    stars: 200_000,
    downloads: 20_000_000,
    npm: 'react',
  },
  vue: {
    url: 'https://vuejs.org/',
    name: 'Vue',
    repo: 'vuejs/vue',
    stars: 201_000,
    downloads: 3_000_000,
    npm: 'vue',
  },
  angular: {
    url: 'https://angular.io/',
    name: 'Angular',
    repo: 'angular/angular',
    stars: 86_000,
    npm: '@angular/core',
    downloads: 3_300_000,
  },
  preact: {
    url: 'https://preactjs.com/',
    name: 'Preact',
    repo: 'preactjs/preact',
    stars: 34_000,
    npm: 'preact',
    downloads: 2_300_000,
  },
  svelte: {
    url: 'https://svelte.dev/',
    name: 'Svelte',
    repo: 'sveltejs/svelte',
    stars: 64_000,
    npm: 'svelte',
    downloads: 427_000,
  },
  alpine: {
    url: 'https://alpinejs.dev/',
    name: 'Alpine',
    npm: 'alpinejs',
    repo: 'alpinejs/alpine',
    downloads: 125_000,
    stars: 22_000,
  },
  angularJs: {
    url: 'https://angularjs.org/',
    name: 'AngularJS',
    repo: 'angular/angular.js',
    lastCommitDate: '2022-01-01',
    stars: 59_000,
    npm: 'angular',
    downloads: 444_000,
  },
  aurelia: {
    name: 'Aurelia',
    url: 'https://aurelia.io/',
    npm: 'aurelia-framework',
    repo: 'aurelia/framework',
    downloads: 12_000,
    stars: 12_000,
    lastCommitDate: '2022-03-31',
  },
  ember: {
    url: 'https://emberjs.com/',
    name: 'Ember',
    repo: 'emberjs/ember.js',
    stars: 22_000,
    npm: 'ember-cli',
    downloads: 175_000,
  },
  inferno: {
    url: 'https://www.infernojs.org/',
    name: 'Inferno',
    repo: 'infernojs/inferno',
    stars: 16_000,
    npm: 'inferno',
    downloads: 115_000,
  },
  lit: {
    name: 'Lit',
    url: 'https://lit.dev/',
    repo: 'lit/lit',
    stars: 13_000,
    npm: 'lit',
    downloads: 506_000,
  },
  mithril: {
    url: 'https://mithril.js.org/',
    name: 'Mithril',
    repo: 'MithrilJS/mithril.js',
    npm: 'mithril',
    downloads: 68_000,
    stars: 13_500,
  },
  polymer: {
    url: 'https://polymer-library.polymer-project.org/',
    name: 'Polymer',
    repo: 'Polymer/polymer',
    stars: 22_000,
    npm: '@polymer/polymer',
    downloads: 83_000,
  },
  solid: {
    url: 'https://www.solidjs.com/',
    name: 'Solid',
    repo: 'solidjs/solid',
    stars: 23_000,
    npm: 'solid-js',
    downloads: 37_000,
  },
  stencil: {
    url: 'https://stenciljs.com/',
    name: 'Stencil',
    repo: 'ionic-team/stencil',
    stars: 11_000,
    npm: '@stencil/core',
    downloads: 512_000,
  },
  qwik: {
    url: 'https://qwik.builder.io/',
    name: 'Qwik',
    repo: 'BuilderIO/qwik',
    stars: 13_000,
    npm: 'create-qwik',
    downloads: 1000,
    isNew: true,
  },
}

export const wrappers = {
  threlte: {
    url: 'https://threlte.xyz/',
    name: 'Threlte',
    repo: 'threlte/threlte',
    stars: 1400,
    npm: '@threlte/core',
    downloads: 5_000,
  },
  svelteCubed: {
    url: 'https://svelte-cubed.vercel.app/',
    name: 'Svelte Cubed',
    repo: 'rich-harris/svelte-cubed',
    stars: 1200,
    npm: 'svelte-cubed',
    downloads: 500,
    lastCommitDate: '2021-11-23',
  },
  tres: {
    name: 'TresJS',
    url: 'https://tresjs.org/',
    repo: 'tresjs/tres',
    stars: 700,
    npm: '@tresjs/core',
    downloads: 500,
  },
  trois: {
    url: 'https://troisjs.github.io/',
    name: 'Trois',
    repo: 'troisjs/trois',
    stars: 3700,
    lastCommitDate: '2023-02-22',
    npm: 'troisjs',
    downloads: 1000,
  },
  lunchbox: {
    name: 'Lunchbox',
    url: 'https://lunchboxjs.com/',
    repo: 'breakfast-studio/lunchboxjs',
    stars: 200,
    npm: 'lunchboxjs',
    downloads: 30,
    lastCommitDate: '2022-11-19',
  },
  angularThree: {
    url: 'https://angular-three.netlify.app/',
    name: 'Angular Three',
    npm: 'angular-three',
    stars: 100,
    downloads: 100,
    repo: 'angular-threejs/angular-three',
  },
  reactBabylon: {
    name: 'react-babylonjs',
    repo: 'brianzinn/react-babylonjs',
    stars: 700,
    npm: 'react-babylonjs',
    downloads: 1700,
  },
  vueBabylon: {
    url: 'https://vue-babylonjs.com',
    name: 'Vue-BabylonJS',
    repo: 'Beg-in/vue-babylonjs',
    stars: 430,
    npm: 'vue-babylonjs',
    downloads: 60,
    lastCommitDate: '2019-06-02',
  },
  svelteBabylon: {
    url: 'https://svelte-babylon.netlify.app/',
    name: 'Svelte-Babylon',
    repo: 'Myrmod/svelte-babylon',
    stars: 14,
    npm: 'svelte-babylon',
    downloads: 10,
  },
  reactPixi: {
    url: 'https://pixijs.io/pixi-react/',
    name: 'Pixi React',
    repo: 'pixijs/pixi-react',
    stars: 1900,
    npm: '@pixi/react',
    downloads: 5000,
  },
  reactPixiFiber: {
    name: 'ReactPixiFiber',
    repo: 'michalochman/react-pixi-fiber',
    stars: 800,
    npm: 'react-pixi-fiber',
    downloads: 800,
    lastCommitDate: '2022-11-25',
  },
  sveltePixi: {
    url: 'https://svelte-pixi.com/docs/getting-started/introduction',
    name: 'Svelte Pixi',
    repo: 'mattjennings/svelte-pixi',
    stars: 80,
    npm: 'svelte-pixi',
    downloads: 80,
    lastCommitDate: '2022-08-23',
  },
  phavuer: {
    name: 'Phavuer',
    repo: 'laineus/phavuer',
    stars: 100,
    npm: 'phavuer',
    downloads: 30,
    // lastCommitDate: '2023-03-28',
  },
  sveltePhaser: {
    name: 'svelte-phaser',
    repo: 'mattjennings/svelte-phaser',
    stars: 80,
    npm: 'svelte-phaser',
    downloads: 15,
    lastCommitDate: '2021-08-22',
  },
  reactPhaserFiber: {
    name: 'react-phaser-fiber',
    repo: 'mattjennings/react-phaser-fiber',
    stars: 50,
    npm: 'react-phaser-fiber',
    downloads: 20,
    lastCommitDate: '2020-04-03',
  },
  reactPhaser: {
    name: 'React-phaser',
    repo: 'evilfer/react-phaser',
    stars: 100,
    npm: 'react-phaser',
    downloads: 10,
    lastCommitDate: '2016-04-22',
  },
  ionPhaser: {
    name: 'IonPhaser',
    repo: 'proyecto26/ion-phaser',
    stars: 240,
    npm: '@ion-phaser/core',
    downloads: 400,
    lastCommitDate: '2021-03-16',
  },
  reactOgl: {
    name: 'react-ogl',
    repo: 'pmndrs/react-ogl',
    npm: 'react-ogl',
    stars: 140,
    downloads: 30,
    lastCommitDate: '2022-10-10',
  },
  svelteOgl: {
    name: 'svelte-ogl',
    repo: 'KotwOSS/svelte-ogl',
    stars: 3,
    npm: 'svelte-ogl',
    downloads: 10,
    lastCommitDate: '2022-12-21',
  },
}

export const reactFrameworks = {
  next: {
    url: 'https://nextjs.org/',
    name: 'Next.js',
    repo: 'vercel/next.js',
    stars: 98_000,
    downloads: 4_400_000,
    npm: 'next',
  },
  gatsby: {
    url: 'https://www.gatsbyjs.com/',
    name: 'Gatsby',
    repo: 'gatsbyjs/gatsby',
    stars: 54_000,
    npm: 'gatsby',
    downloads: 1_600_000,
  },
  cra: {
    url: 'https://create-react-app.dev/',
    name: 'Create React App',
    repo: 'facebook/create-react-app',
    stars: 98_000,
    npm: 'react-scripts',
    downloads: 3_600_000,
  },
  vite: {
    url: 'https://vitejs.dev/',
    name: 'Vite',
    repo: 'vitejs/vite',
    stars: 51_000,
    npm: 'vite',
    downloads: 2_200_000,
  },
  remix: {
    url: 'https://remix.run/',
    name: 'Remix',
    repo: 'remix-run/remix',
    stars: 21_000,
    npm: '@remix-run/react',
    downloads: 85_000,
  },
  astro: {
    url: 'https://astro.build/',
    name: 'Astro',
    repo: 'withastro/astro',
    stars: 24_000,
    npm: 'astro',
    downloads: 40_000,
  },
}

export const typescript = {
  name: 'TypeScript',
  url: 'https://www.typescriptlang.org/',
  repo: 'microsoft/TypeScript',
  stars: 87_000,
  npm: 'typescript',
  downloads: 43_000_000,
}

export const animations = {
  animeJs: {
    name: 'anime.js',
    url: 'https://animejs.com/',
    repo: 'juliangarnier/anime',
    npm: 'animejs',
    stars: 44_000,
    downloads: 140_000,
    lastCommitDate: '2020-10-15',
  },
  framerMotion3d: {
    url: 'https://www.framer.com/docs/three-introduction/',
    name: 'Framer Motion 3D',
    repo: 'framer/motion',
    stars: 17_000,
    npm: 'framer-motion-3d',
    downloads: 2000,
    isNew: true,
  },
  gsap: {
    url: 'https://greensock.com/',
    name: 'GSAP',
    repo: 'greensock/GSAP',
    stars: 15_000,
    npm: 'gsap',
    downloads: 368_000,
  },
  motionOne: {
    name: 'Motion One',
    url: 'https://motion.dev/',
    repo: 'motiondivision/motionone',
    stars: 800,
    downloads: 15_000,
    npm: 'motion',
  },
  popmotion: {
    url: 'https://popmotion.io/',
    name: 'Popmotion',
    repo: 'popmotion/popmotion',
    stars: 19_000,
    npm: 'popmotion',
    downloads: 1_700_000,
  },
  reactSpring: poimandres.reactSpring,
  tweenJs: {
    name: 'tween.js',
    url: 'https://tweenjs.github.io/tween.js/',
    repo: 'tweenjs/tween.js/',
    stars: 9000,
    npm: '@tweenjs/tween.js',
    downloads: 218_000,
    lastCommitDate: '2021-10-24',
  },
  theatre,
}

export const audio = {
  howler: {
    url: 'https://howlerjs.com/',
    name: 'Howler',
    repo: 'goldfire/howler.js',
    stars: 21_000,
    npm: 'howler',
    downloads: 221_000,
  },
  tuna: {
    name: 'tuna',
    repo: 'Theodeus/tuna',
    stars: 1600,
    npm: 'tunajs',
    downloads: 200,
  },
  pizzicato: {
    name: 'Pizzicato',
    repo: 'alemangui/pizzicato',
    stars: 1500,
    lastCommitDate: '2020-03-22',
    npm: 'pizzicato',
    downloads: 500,
  },
  reactronica: {
    url: 'https://reactronica.com/',
    name: 'Reactronica',
    repo: 'unkleho/reactronica',
    stars: 400,
    npm: 'reactronica',
    downloads: 40,
  },
  reactMusic: {
    name: 'react-music',
    repo: 'FormidableLabs/react-music',
    stars: 2700,
    npm: 'react-music',
    downloads: 10,
    lastCommitDate: '2018-03-16',
  },
  soundJs: {
    name: 'SoundJS',
    repo: 'CreateJS/SoundJS',
    stars: 4300,
    npm: 'soundjs',
    downloads: 300,
    lastCommitDate: '2017-10-17',
  },
  tone: {
    name: 'Tone.js',
    url: 'https://tonejs.github.io/',
    repo: 'Tonejs/Tone.js',
    stars: 12_100,
    npm: 'tone',
    downloads: 13_000,
  },
  wad: {
    name: 'WadJS',
    repo: 'rserota/wad',
    stars: 1700,
    npm: 'web-audio-daw',
    downloads: 400,
  },
  xsound: {
    name: 'XSound',
    repo: 'Korilakkuma/XSound',
    stars: 170,
    npm: 'xsound',
    downloads: 200,
  },
}

export const physics = {
  ammo: {
    name: 'ammo.js',
    repo: 'kripken/ammo.js',
    stars: 3300,
  },
  cannonEs: poimandres.cannonEs,
  cannonJs: {
    name: 'cannon.js',
    repo: 'schteppe/cannon.js',
    npm: 'cannon',
    stars: 4100,
    downloads: 3800,
    lastCommitDate: '2016-05-03',
  },
  oimo: {
    name: 'Oimo.js',
    repo: 'lo-th/Oimo.js',
    stars: 2700,
    npm: 'oimo',
    downloads: 700,
    lastCommitDate: '2017-06-20',
  },
  rapier: {
    name: 'Rapier',
    repo: 'dimforge/rapier',
    url: 'https://rapier.rs/docs/user_guides/javascript/getting_started_js/',
    stars: 2000,
    npm: '@dimforge/rapier3d-compat',
    downloads: 5000,
    isNew: true,
  },
  useCannon: poimandres.useCannon,
}

export const webWorkers = {
  comlink: {
    name: 'Comlink',
    repo: 'GoogleChromeLabs/comlink',
    stars: 9100,
    downloads: 196_000,
    npm: 'comlink',
  },
  threads: {
    name: 'threads.js',
    url: 'https://threads.js.org/',
    repo: 'andywer/threads.js',
    stars: 2700,
    npm: 'threads',
    downloads: 116_000,
    lastCommitDate: '2021-09-26',
  },
  workerpool: {
    name: 'workerpool',
    repo: 'josdejong/workerpool',
    stars: 1500,
    npm: 'workerpool',
    downloads: 5_400_000,
  },
  troikaWorkerUtils: {
    url: 'https://protectwise.github.io/troika/troika-worker-utils/',
    name: 'troika-worker-utils',
    repo: 'protectwise/troika',
    npm: 'troika-worker-utils',
    downloads: 106_000,
  },
  comlinkLoader: {
    name: 'comlink-loader',
    repo: 'GoogleChromeLabs/comlink-loader',
    stars: 600,
    downloads: 7000,
    npm: 'comlink-loader',
    lastCommitDate: '2020-01-15',
  },
  greenlet: {
    name: 'Greenlet',
    repo: 'developit/greenlet',
    stars: 4600,
    npm: 'greenlet',
    downloads: 900,
    lastCommitDate: '2019-10-16',
  },
  workerize: {
    name: 'Workerize',
    repo: 'developit/workerize',
    stars: 4300,
    npm: 'workerize',
    downloads: 700,
    lastCommitDate: '2019-12-28',
  },
  workerizeLoader: {
    name: 'workerize-loader',
    repo: 'developit/workerize-loader',
    stars: 2200,
    npm: 'workerize-loader',
    downloads: 17_000,
  },
}

export const others = {
  offscreencanvasPolyfill: {
    name: 'offscreen-canvas',
    repo: 'ai/offscreen-canvas',
    stars: 300,
    lastCommitDate: '2019-07-13',
    npm: 'offscreen-canvas',
    downloads: 300,
  },
}

export const ecs = {
  ape: {
    name: 'Ape-ECS',
    repo: 'fritzy/ape-ecs',
    stars: 240,
    downloads: 60,
    npm: 'ape-ecs',
    lastCommitDate: '2021-02-04',
  },
  becsy: {
    name: 'Becsy',
    repo: 'LastOliveGames/becsy',
    stars: 130,
    npm: '@lastolivegames/becsy',
    downloads: 2500,
  },
  bitecs: {
    name: 'bitECS',
    repo: 'NateTheGreatt/bitECS',
    stars: 700,
    npm: 'bitecs',
    downloads: 600,
  },
  ecsLib: {
    name: 'ecs-lib',
    repo: 'nidorx/ecs-lib',
    stars: 150,
    npm: 'ecs-lib',
    downloads: 50,
  },
  ecsy: {
    name: 'ECSY',
    repo: 'ecsyjs/ecsy',
    stars: 1100,
    downloads: 500,
    npm: 'ecsy',
    lastCommitDate: '2020-09-10',
  },
  entComp: {
    name: 'EntComp',
    repo: 'fenomas/ent-comp',
    stars: 25,
    downloads: 200,
    npm: 'ent-comp',
  },
  geotic: {
    name: 'Geotic',
    repo: 'ddmills/geotic',
    npm: 'geotic',
    stars: 150,
    downloads: 100,
    lastCommitDate: '2022-03-21',
  },
  harmony: {
    name: 'Harmony ECS',
    npm: 'harmony-ecs',
    stars: 30,
    downloads: 30,
    repo: '3mcd/harmony-ecs',
    lastCommitDate: '2021-12-01',
  },
  javelin: {
    name: 'Javelin',
    repo: '3mcd/javelin',
    npm: '@javelin/ecs',
    stars: 170,
    downloads: 100,
  },
  miniplex: {
    name: 'Miniplex',
    repo: 'hmans/miniplex',
    stars: 500,
    npm: 'miniplex',
    downloads: 700,
  },
  nanoECS: {
    name: 'Nano ECS',
    repo: 'hackergrrl/nano-ecs',
    npm: 'nano-ecs',
    stars: 60,
    downloads: 20,
    lastCommitDate: '2020-05-28',
  },
  performECS: {
    name: 'Perform ECS',
    repo: 'fireveined/perform-ecs',
    stars: 30,
    downloads: 30,
    npm: 'perform-ecs',
    lastCommitDate: '2019-06-18',
  },
  picoes: {
    name: 'PicoES',
    repo: 'ayebear/picoes',
    stars: 10,
    npm: 'picoes',
    downloads: 90,
    // lastCommitDate: '2022- 05-11'
  },
  piecs: {
    name: 'PIECS',
    repo: 'sondresj/piecs',
    stars: 30,
    lastCommitDate: '2021-11-07',
    npm: 'piecs',
    downloads: 30,
  },
  reactECS: {
    name: 'React ECS',
    repo: 'dustinlacewell/react-ecs',
    npm: '@react-ecs/core',
    stars: 70,
    downloads: 290,
    lastCommitDate: '2021-12-12',
  },
  thyseus: {
    name: 'Thyseus',
    repo: 'JaimeGensler/thyseus',
    stars: 40,
    npm: 'thyseus',
    downloads: 320,
  },
  tickKnock: {
    name: 'Tick-Knock',
    repo: 'mayakwd/tick-knock',
    stars: 100,
    npm: 'tick-knock',
    downloads: 300,
  },
  tinyECS: {
    name: 'TinyECS',
    repo: 'bvalosek/tiny-ecs',
    stars: 50,
    npm: 'tiny-ecs',
    downloads: 30,
    lastCommitDate: '2014-02-07',
  },
  uecs: {
    name: 'μECS',
    repo: 'jprochazk/uecs',
    npm: 'uecs',
    stars: 30,
    downloads: 60,
    lastCommitDate: '2021-11-18',
  },
  yagl: {
    name: 'Yagl',
    repo: 'yagl/ecs',
    lastCommitDate: '2016-03-27',
    stars: 120,
    npm: 'yagl-ecs',
    downloads: 30,
  },
}

export const protobuf = {
  googleProtobuf: {
    name: 'google-protobuf',
    repo: 'protocolbuffers/protobuf-javascript',
    npm: 'google-protobuf',
    downloads: 1_000_000,
    stars: 70,
  },
  protobufJs: {
    name: 'protobuf.js',
    repo: 'protobufjs/protobuf.js',
    stars: 9000,
    npm: 'protobufjs',
    downloads: 8_000_000,
  },
  protobufEs: {
    name: 'protobuf-es',
    repo: 'bufbuild/protobuf-es',
    stars: 400,
    npm: '@bufbuild/protobuf',
    downloads: 7000,
    isNew: true,
  },
  tsProto: {
    name: 'ts-proto',
    repo: 'stephenh/ts-proto',
    stars: 1200,
    npm: 'ts-proto',
    downloads: 90_000,
  },
  protobufTs: {
    name: 'protobuf-ts',
    repo: 'timostamm/protobuf-ts',
    stars: 500,
    npm: '@protobuf-ts/plugin',
    downloads: 38_000,
  },
  protocGenTs: {
    name: 'protoc-gen-ts',
    repo: 'thesayyn/protoc-gen-ts',
    stars: 200,
    npm: 'protoc-gen-ts',
    downloads: 20_000,
  },
  protocolBuffers: {
    name: 'protocol-buffers',
    repo: 'mafintosh/protocol-buffers',
    stars: 700,
    npm: 'protocol-buffers',
    downloads: 20_000,
    lastCommitDate: '2022-03-23',
  },
}

export const reactQuery = {
  url: 'https://tanstack.com/query',
  name: 'React Query',
  repo: 'TanStack/query',
  stars: 31_000,
  npm: '@tanstack/react-query',
  downloads: 486_000,
}

export const graphql = {
  apolloServer: {
    name: 'Apollo Server',
    repo: 'apollographql/apollo-server',
  },
}

export const trpc = {
  url: 'https://trpc.io/',
  name: 'tRPC',
  npm: '@trpc/server',
  repo: 'trpc/trpc',
  stars: 15_000,
  downloads: 81_000,
}

export const webrtc = {
  peerJs: {
    url: 'https://peerjs.com/',
    name: 'PeerJS',
    repo: 'peers/peerjs',
    stars: 10_000,
    npm: 'peerjs',
    downloads: 14_000,
  },
  simplePeer: {
    name: 'SimplePeer',
    repo: 'feross/simple-peer',
    stars: 6500,
    npm: 'simple-peer',
    downloads: 21_000,
  },
  geckos: {
    name: 'Geckos.io',
    repo: 'geckosio/geckos.io',
    npm: '@geckos.io/server',
    stars: 1000,
    downloads: 700,
  },
  nodeDataChannel: {
    name: 'node-datachannel',
    repo: 'murat-dogan/node-datachannel',
    stars: 150,
    npm: 'node-datachannel',
    downloads: 4300,
  },
  nodeWebRtc: {
    name: 'node-webrtc',
    repo: 'node-webrtc/node-webrtc',
    stars: 2500,
    npm: 'wrtc',
    downloads: 10_000,
  },
  webUdp: {
    name: 'web-udp',
    repo: '3mcd/web-udp',
    stars: 50,
    npm: '@web-udp/client',
    downloads: 20,
    lastCommitDate: '2020-05-04',
  },
}

export const random = {
  alea: {
    name: 'alea',
    repo: 'coverslide/node-alea',
    stars: 70,
    npm: 'alea',
    downloads: 8000,
    lastCommitDate: '2021-09-08',
  },
  numberGenerator: {
    name: 'Number Generator',
    repo: 'MartinHelmut/number-generator',
    stars: 10,
    npm: 'number-generator',
    downloads: 1200,
  },
  prando: {
    name: 'Prando',
    repo: 'zeh/prando',
    stars: 100,
    npm: 'prando',
    downloads: 14_000,
    lastCommitDate: '2021-05-01',
  },
  random: {
    name: 'random',
    repo: 'transitive-bullshit/random',
    stars: 100,
    npm: 'random',
    downloads: 37_000,
  },
  randomJs: {
    name: 'random-js',
    repo: 'ckknight/random-js',
    stars: 600,
    downloads: 60_000,
    lastCommitDate: '2019-05-31',
  },
  randomSeed: {
    name: 'random-seed',
    repo: 'skratchdot/random-seed',
    stars: 100,
    npm: 'random-seed',
    downloads: 165_000,
    lastCommitDate: '2015-06-02',
  },
  seedDashRandom: {
    name: 'seed-random',
    repo: 'ForbesLindesay/seed-random',
    stars: 40,
    npm: 'seed-random',
    downloads: 900_000,
    lastCommitDate: '2013-11-11',
  },
  seedRandom: {
    name: 'seedrandom.js',
    repo: 'davidbau/seedrandom',
    stars: 1800,
    npm: 'seedrandom',
    downloads: 1_370_000,
    lastCommitDate: '2019-09-17',
  },
  thingRandom: {
    url: 'https://www.npmjs.com/package/@thi.ng/random',
    name: 'thi.ng/random',
    repo: 'thi-ng/umbrella',
    npm: '@thi.ng/random',
    downloads: 74_000,
  },
}

export const noise = {
  fastSimplexNoise: {
    name: 'fast-simplex-noise',
    repo: 'joshforisha/fast-simplex-noise-js',
    stars: 60,
    npm: 'fast-simplex-noise',
    downloads: 350,
    lastCommitDate: '2017-02-17',
  },
  fractalNoise: {
    name: 'fractal-noise',
    npm: 'fractal-noise',
    repo: 'joshforisha/fractal-noise-js',
    stars: 40,
    downloads: 40,
  },
  simplexNoise: {
    name: 'simplex-noise.js',
    repo: 'jwagner/simplex-noise.js',
    stars: 1200,
    npm: 'simplex-noise',
    downloads: 16_000,
  },
  openSimplexNoise: {
    name: 'open-simplex-noise',
    repo: 'joshforisha/open-simplex-noise-js',
    stars: 120,
    npm: 'open-simplex-noise',
    downloads: 300,
    lastCommitDate: '2021-04-27',
  },
  tumult: {
    name: 'tumult',
    repo: 'philipjscott/tumult',
    stars: 40,
    npm: 'tumult',
    downloads: 1000,
    lastCommitDate: '2019-12-02',
  },
}

export const gameFrameworks = {
  colyseus: {
    url: 'https://colyseus.io/',
    name: 'Colyseus',
    repo: 'colyseus/colyseus',
    stars: 4500,
    npm: 'colyseus',
    downloads: 2800,
  },
  actionhero: {
    url: 'https://www.actionherojs.com/',
    name: 'Actionhero',
    repo: 'https://github.com/actionhero/actionhero',
    stars: 2300,
    npm: 'actionhero',
    downloads: 5500,
  },
  pomelo: {
    name: 'Pomelo',
    repo: 'NetEase/pomelo',
    stars: 11_600,
    npm: 'pomelo',
    downloads: 300,
    lastCommitDate: '2019-11-08',
  },
  lance: {
    name: 'Lance',
    url: 'https://lance-gg.github.io/',
    repo: 'lance-gg/Lance',
    stars: 1400,
    npm: 'lance-gg',
    downloads: 40,
    lastCommitDate: '2020-01-11',
  },
  boardGameIo: {
    url: 'https://boardgame.io',
    name: 'boardgame.io',
    repo: 'boardgameio/boardgame.io',
    stars: 9400,
    npm: 'boardgame.io',
    downloads: 900,
  },
  nengi: {
    name: 'nengi',
    repo: 'timetocode/nengi',
    stars: 300,
    npm: 'nengi',
    downloads: 10,
    lastCommitDate: '2022-03-22',
  },
}

export const desktop = {
  electron: {
    url: 'https://www.electronjs.org/',
    name: 'Electron',
    repo: 'electron/electron',
    stars: 106_000,
    npm: 'electron',
    downloads: 645_000,
  },
  tauri: {
    url: 'https://tauri.app/',
    name: 'Tauri',
    repo: 'tauri-apps/tauri',
    stars: 60_000,
    npm: '@tauri-apps/cli',
    downloads: 20_000,
  },
  nw: {
    url: 'https://nwjs.io/',
    name: 'NW.js',
    repo: 'nwjs/nw.js',
    stars: 40_000,
  },
  nodeGui: {
    name: 'NodeGui',
    url: 'https://docs.nodegui.org/',
    repo: 'nodegui/nodegui',
    stars: 8300,
    npm: '@nodegui/nodegui',
    downloads: 700,
  },
  gluon: {
    url: 'https://gluonjs.org/',
    name: 'Gluon',
    repo: 'gluon-framework/gluon',
    stars: 2600,
    npm: '@gluon-framework/gluon',
    downloads: 100,
    isNew: true,
  },
  neutralino: {
    name: 'Neutralinojs',
    repo: 'neutralinojs/neutralinojs',
    url: 'https://neutralino.js.org/',
    stars: 6400,
    npm: '@neutralinojs/neu',
    downloads: 400,
  },
  wails: {
    name: 'Wails',
    url: 'https://wails.io/',
    repo: 'wailsapp/wails',
    stars: 14_300,
  },
}

export const steam = {
  steamworksjs: {
    name: 'Steamworks.js',
    repo: 'ceifa/steamworks.js',
    stars: 115,
    npm: 'steamworks.js',
    downloads: 300,
    isNew: true,
  },
  communityGreenworks: {
    name: 'Greenworks (community fork)',
    repo: 'greenworksjs/greenworks',
    stars: 15,
    lastCommitDate: '2022-02-25',
  },
  greenworks: {
    name: 'Greenworks',
    repo: 'greenheartgames/greenworks',
    stars: 1300,
    lastCommitDate: '2018-11-18',
  },
}

export const rust = {
  bevy: {
    url: 'https://bevyengine.org/',
    name: 'Bevy',
    repo: 'bevyengine/bevy',
    stars: 22_000,
    crate: 'bevy',
    crateDownloads: 400_000,
  },
  ggez: {
    url: 'https://ggez.rs/',
    name: 'ggez',
    repo: 'ggez/ggez',
    stars: 3700,
    crate: 'ggez',
    crateDownloads: 150_000,
  },
  macroquad: {
    name: 'macroquad',
    repo: 'not-fl3/macroquad',
    stars: 2000,
    crate: 'macroquad',
    crateDownloads: 100_000,
  },
  amethyst: {
    url: 'https://amethyst.rs/',
    name: 'Amethyst',
    repo: 'amethyst/amethyst',
    stars: 7900,
    crate: 'amethyst',
    crateDownloads: 170_000,
    lastCommitDate: '2021-10-23',
  },
  ambient: {
    url: 'https://www.ambient.run/',
    repo: 'AmbientRun/Ambient',
    stars: 2500,
    name: 'Ambient',
    crate: 'ambient_api',
    crateDownloads: 400,
    isNew: true,
  },
  fyrox: {
    name: 'Fyrox',
    url: 'https://fyrox.rs/',
    repo: 'FyroxEngine/Fyrox',
    stars: 6000,
    crate: 'fyrox',
    crateDownloads: 5700,
  },
  piston: {
    name: 'Piston',
    url: 'https://www.piston.rs/',
    repo: 'PistonDevelopers/piston',
    stars: 4300,
    crate: 'piston',
    crateDownloads: 690_000,
    lastCommitDate: '2020-05-31',
  },
  wgpu: {
    name: 'wgpu',
    url: 'https://wgpu.rs/',
    repo: 'gfx-rs/wgpu',
    stars: 7000,
    crate: 'wgpu',
    crateDownloads: 1_800_000,
  },
  wasmPack: {
    name: 'wasm-pack',
    repo: 'rustwasm/wasm-pack',
    url: 'https://rustwasm.github.io/wasm-pack/',
    stars: 5000,
    crate: 'wasm-pack',
    crateDownloads: 550_000,
  },
  trunk: {
    url: 'https://trunkrs.dev/',
    name: 'Trunk',
    repo: 'thedodd/trunk',
    stars: 2300,
    crate: 'trunk',
    crateDownloads: 112_000,
  },
  rocket: {
    url: 'https://rocket.rs/',
    name: 'Rocket',
    repo: 'SergioBenitez/Rocket',
    stars: 20_000,
    crate: 'rocket',
    crateDownloads: 2_700_000,
  },
  actix: {
    name: 'Actix Web',
    url: 'https://actix.rs/',
    repo: 'actix/actix-web',
    stars: 17_000,
    crate: 'actix-web',
    crateDownloads: 10_000_000,
  },
  warp: {
    name: 'warp',
    repo: 'seanmonstar/warp',
    stars: 7800,
    crate: 'warp',
    crateDownloads: 8_000_000,
  },
  axum: {
    repo: 'tokio-rs/axum',
    stars: 8800,
    name: 'axum',
    crate: 'axum',
    crateDownloads: 9_000_000,
  },
  poem: {
    name: 'poem',
    repo: 'poem-web/poem',
    crate: 'poem',
    crateDownloads: 600_000,
  },
  hyper: {
    url: 'https://hyper.rs/',
    repo: 'hyperium/hyper',
    stars: 11_000,
    name: 'hyper',
    crate: 'hyper',
    crateDownloads: 74_000_000,
  },
  tide: {
    name: 'tide',
    repo: 'http-rs/tide',
    stars: 4100,
    crate: 'tide',
    crateDownloads: 890_000,
  },
  rouille: {
    name: 'rouille',
    repo: 'tomaka/rouille',
    stars: 900,
    crate: 'rouille',
    crateDownloads: 1_000_000,
  },
  iron: {
    name: 'iron',
    repo: 'iron/iron',
    stars: 6100,
    crate: 'iron',
    crateDownloads: 1_200_000,
  },
}
